---
jobs:
- name: update-concourse-task-image
  plan:
  - get: concourse-images
    trigger: true
  - put: concourse-tasks-image-repo
    params:
      build: concourse-images/task/concourse-tasks
      tag_file: concourse-images/VERSION
      tag_as_latest: true
- name: update-oracle-image-task
  plan:
  - get: oracle-image-git-repository
    trigger: true
  - put: oracle-image-repository
    params:
      build: oracle-image-git-repository/OracleInstantClient/oraclelinux7/19
- name: update-sql-client-image
  plan:
  - in_parallel:
      steps:
      - get: concourse-images
        trigger: true
      - get: oracle-image-repository
        passed: [update-oracle-image-task]
        trigger: true
  - put: sql-image-repo
    params:
      build: concourse-images/task/sql-image

- name: s3-resource-simple-image
  plan:
    - get: alpine-image
      params:
        skip_download: true
      trigger: true
    - get: s3-resource-simple-repository
    - put: s3-resource-simple-repo
      params:
        build: s3-resource-simple-repository

resources:
- name: concourse-images
  type: git
  source:
    uri: {{concourse-task-image-git-url}}
    branch: {{concourse-task-image-git-branch}}

- name: sql-image-repo
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{sql-image-repository}}

- name: concourse-tasks-image-repo
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{concourse-tasks-repository}}

- name: oracle-image-git-repository
  type: git
  source:
    uri: {{oracle-image-git-repository}}
    branch: {{oracle-image-git-repository-branch}}

- name: oracle-image-repository
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{oracle-image-repository}}

- name: s3-resource-simple-repository
  type: git
  source:
    uri: {{s3-resource-simple-git-repository}}
    branch: {{s3-resource-simple-git-repository-branch}}

- name: s3-resource-simple-repo
  type: docker-image
  source:
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{s3-resource-simple-image-repository}}

- name: alpine-image
  type: docker-image
  source:
    repository: alpine
